Enh: relay all states transitions to behavior algo dedicated thread (#247)
* Clean unused

* log

* clean: was removed

* Also protect from callbacks exception here

* Enh process_hand_data: reuse row_index + lengths

* Use AllHandsParts + cleans + comments

* Add pellet_hand_uncover_distance to PelletDeliveryConfiguration

* Handle pellet hands min distance and add to algo.can_release_pellet

* add Hands near pellet dev button

* clean

* Missed re-save pellet_hand_uncover_distance

* Better name + add debug

* Default to 5 and buffer result to hands_near_pellet_seen

* fix: need check None for pellet_hand_uncover_distance

* use lower-equal for near seen

* log bettr/less noisy

* clean

* Enh: call try_next_state/env_changed from handler

* add log here

* better log

* Is a trigger

* clean

* move outside loop block

* Enh: use transitions_allow_functions

This allows to see the trigger/before/after/conditions function referenced.

Otherwise you don't see them being used anywhere, but only the trigger.

* Fix: missed assign self._timer_check_missing

* Rename _system_message_handler for clarity

* Relay to system message handler

* Fix: msg_handler is None in some tests

* Continue relay_to_system_message_handler

* Better names + allow callable for SystemMessageHandler.relay_func

* Fix: missed

* clean

* Enh: allow relay_transitions to system message handler

* Enh: use the full trigger to relay to system msg handler, so that the full transitions are executed on it, not only the before&after, but everything

* Enh/Fix: only relay the trigger transition functions

* Fix: it's the transition method name that must be used

* Fix: _config is already used by Process that we subclass

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/util.py", line 351, in _exit_function
    if p.daemon:
  File "/usr/lib/python3.8/multiprocessing/process.py", line 203, in daemon
    return self._config.get('daemon', False)
AttributeError: 'LogConfig' object has no attribute 'get'

* Enh: CanInterface: also use time.perf_counter for duration/delay/timeout handling

* Fix: wrapper for bound method != wrapper for pure function

* Fix: BehaviorAlgorithm._diamond_triangle_offset_config missed to be set when no config file available

* Also bypass partial(s)

* Retry

* Like this

* Also add segment_config to can_perform_detection

* Also use segment_config arg here

* simplify/clean

* Fix: missed msg_handler can be None in tests.

* Enh: by default wait on completion of put_func_call.

* Fix: need start system message handler thread immediatelly

* Enh: use thread locals to not re-create a new event for each put_func_call

* Use better is not None

* Fix: always set event, even if exception

* can_perform_detection: add check segment_config is not None + clean + comment

* SystemMachine: on HANDS_NEAR_PELLET_SEEN changed: self._pellet_machine.environment_changed

* Fix: need set hands_near_pellet_seen before calling the change event

* Move to behavior

* Like this

* Enh: allow some test to works still

* Retry wait=False

* Also disable here

* Fix: start|end_session must not be relayed. But can do on inner one.

* Directly use BehaviorAlgorithm.relay_func

* Enh: allow set_put_func_call_mode per thread + use it for different handlers

* _check_presence_missing: use wait=False

* Add test test_set_put_func_call_mode

* Use single relay_func

* Enh and simplify BehaviorAlgorithm handler thread and queue handling

* Also use wait=False for _load_cell_monitor_property_changed + _consider_end_session

* Enh algo handler ; close at exit + small clean docstr & comments

* Enh/Fix: stop_multiproc_logging also remove the WithThreadIdQueueHandler handler if present

* Enh/Fix: remove TextBoxHandler from root logger handlers on app close

to not eventually get:

RuntimeError: Internal C++ object (QSignaler) already deleted.

if some logger try log smth after app/window closed (which can happen in some atexit registered code too)

* Add comment

* Comment + docstr