Enh: better audio thrashing monitor, use real data (issue-280) (#283)
* Fix RuntimeError due to plot not added to main content

Traceback (most recent call last):
  File "/home/greg/Projects/toptal/Anschutz/auto-trainer/tools/head_fix/view/main_content.py", line 77, in refresh_data
    plot.use_cache()
  File "/home/greg/Projects/toptal/Anschutz/auto-trainer/auto-trainer-pyside/src/autotrainer/pyside/PGWidget.py", line 84, in use_cache
    self.replace(values)
  File "/home/greg/Projects/toptal/Anschutz/auto-trainer/auto-trainer-pyside/src/autotrainer/pyside/PGWidget.py", line 43, in replace
    self._data_line.setData(self.x, self.y)
  File "/home/greg/.virtualenvs/auto-trainer-3.8/lib/python3.8/site-packages/pyqtgraph/graphicsItems/PlotDataItem.py", line 819, in setData
    self.updateItems( styleUpdate = self.property('styleWasChanged') )
RuntimeError: Internal C++ object (PlotDataItem) already deleted.

* Enh audio + fix csv: header missed 32 last bins

* Fix: check None before unpack

* Enh emulation interface: allow replay audio data

* Missed

* Better audio thrashing monitor